ci(buil-apk): fix unexpected symbol

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,19 +30,62 @@ jobs:
 
   # ui-test:
 
-  export-results:
-    needs: [lint, unit-test]
+  build-apk:
+    if: success() && github.ref == 'refs/heads/master'
     runs-on: self-hosted
-    outputs:
-      all_tests_passed: ${{ !contains(needs.*.result, 'failure') }}
     steps:
-      - name: Check if all tests passed
-        run: |
-          echo ${{ !contains(needs.*.result, 'failure') }}
+      - uses: actions/checkout@v4.2.2
 
-  call-build-apk:
-    needs: export-results
-    if: github.ref == 'refs/heads/master' && needs.export-results.outputs.all_tests_passed == 'true'
-    uses: LaPockett/Multiplatform/.github/workflows/build-apk.yml@master
-    with:
-      all_tests_passed: ${{ needs.export-results.outputs.all_tests_passed }}
+      - name: Set current date as env variable
+        run: echo "date_today=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
+
+      - name: Set repository name as env variable
+        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
+
+      - name: Decode key from base64
+        run: |
+          echo "${{ secrets.ANDROID_STORE_BASE64}}" | base64 -d > composeApp/key.jks
+          ls -la composeApp/
+      - name: Verify keystore (optional)
+        run: |
+          keytool -list -v -keystore composeApp/key.jks -storepass ${{ secrets.ANDROID_STORE_PASSWORD }} -alias ${{ secrets.ANDROID_KEY_ALIAS }}
+        continue-on-error: true
+      - run: find . -name "*jks"
+      - name: Change wrapper permissions
+        run: chmod +x ./gradlew
+      - name: Build apk release project ${{ env.MAIN_PROJECT_MODULE }}
+        run: ./gradlew :composeApp:assembleRelease --stacktrace
+        env:
+          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
+          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
+          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
+          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks
+      - name: Build apk debug project ${{ env.MAIN_PROJECT_MODULE }}
+        run: ./gradlew :composeApp:assembleDebug --stacktrace
+        env:
+          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
+          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
+          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
+          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks
+      - name: Find the APK
+        id: find_apk
+        run: |
+          APK_PATH=$(find composeApp/ -path '*/apk/release/*.apk' -o -path '*/outputs/apk/release/*.apk' | head -1)
+          echo "APK_PATH=${APK_PATH}" >> $GITHUB_OUTPUT
+          echo "Found APK at: ${APK_PATH}"
+          if [ -z "${APK_PATH}" ]; then
+            echo "APK not found!"
+            find . -name "*.apk"
+            exit 1
+          fi
+      - name: Upload APK release
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.repository_name }}  - APK Release generated
+          path: ${{steps.find_apk.outputs.APK_PATH}}
+
+      - name: Upload APK debug
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.repository_name }}  - APK Debug generated
+          path: ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/debug/
